name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: make ci

      - run: goreleaser release --rm-dist --snapshot
        if: ${{ runner.os == 'Linux' }}

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.os }}
          path: dist
